name: "n8n_dbt"
version: "1.0.0"
config-version: 2

profile: "n8n_dbt"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  n8n_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
